@startuml
'Object Diagram for exercise 5 - composition
object "root : Folder" as root
root : folderName = "php_demo1"

object "sourceFiles : Folder" as sourceFiles
sourceFiles : folderName = "Source Files"

'Subfolders inside folder 'Source Files'
object ".phalcon : Folder" as phalcon
phalcon : folderName = ".phalcon"

object "app : Folder" as app
app : folderName = "app"

object "cache : Folder" as cache
cache : folderName = "cache"

object "public : Folder" as public
public : folderName = "public"

'Subfolders inside folder 'app'
object "config : Folder" as config
config : folderName = "config"

object "controllers : Folder" as controllers
controllers : folderName = "controllers"

object "library : Folder" as library
library : folderName = "library"

object "migrations : Folder" as migrations
migrations : folderName = "migrations"

object "models : Folder" as models
models : folderName = "models"

object "views : Folder" as views
views : folderName = "views"

'Files inside subfolder 'public'
object ".htaccess : File" as htaccess
htaccess : fileName = ".htaccess"

object "htrouter.php : File" as htrouterphp
htrouterphp : fileName = ".htrouter.php"

object "index.html : File" as indexhtml
indexhtml : fileName = "index.html"

'Composition relationship *--
'Folder 'php_demo1' (root) contains folder 'Source Files'
root *-- sourceFiles

'Folder 'Source Files' contains the following subfolders
sourceFiles *-- phalcon
sourceFiles *-- app
sourceFiles *-- cache
sourceFiles *-- public

'Folder 'app' contains the following subfolders
app *-- config
app *-- controllers
app *-- library
app *-- migrations
app *-- models
app *-- views

'Subfolder 'public' contains the following files
public *-- htaccess
public *-- htrouterphp
public *-- indexhtml

@enduml