@startuml
'Object Diagram

object "ship : Ship" as ship
ship : name = "Astronomy"
ship : yearBuilt = "1999"

object "cruiseShip : CruiseShip" as cruiseShip
cruiseShip : name = "Princess"
cruiseShip : yearBuilt = "2009"
cruiseShip : maxPassengers = 300

object "cargoShip : CargoShip" as cargoShip
cargoShip : name = "Zim Rotterdam"
cargoShip : yearBuilt = "2019"
cargoShip : capacity = 3000

@enduml
